/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-11-04 06:45:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class member_005finput_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<script type=\"text/javascript\">\r\n");
      out.write("			function check(){\r\n");
      out.write("				if (f.id.value==\"\"){\r\n");
      out.write("					alert(\"아이디를 입력해 주세요!!\")\r\n");
      out.write("					f.id.focus()\r\n");
      out.write("					return\r\n");
      out.write("				}\r\n");
      out.write("				if (f.passwd.value==\"\"){\r\n");
      out.write("					alert(\"비밀번호를 입력해 주세요!!\")\r\n");
      out.write("					f.passwd.focus()\r\n");
      out.write("					return\r\n");
      out.write("				}\r\n");
      out.write("				document.f.submit()\r\n");
      out.write("			}\r\n");
      out.write("		</script>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>	\r\n");
      out.write("		<form name=\"f\" method=\"post\" action=\"input_member.do\">\r\n");
      out.write("			<table width=\"550\" align=\"center\" class=\"outline\">\r\n");
      out.write("  				<tr>\r\n");
      out.write("					<td colspan=\"2\" align=center class=\"m2\">회원가입</td>\r\n");
      out.write(" 				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td width=\"150\" class=\"m3\">이름</td>\r\n");
      out.write("					<td class=\"m3\">\r\n");
      out.write("						<input type=\"text\" name=\"name\" class=\"box\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled>\r\n");
      out.write("						<input type=\"hidden\" name=\"name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td width=\"150\" class=\"m3\">아이디</td>\r\n");
      out.write("					<td class=\"m3\">\r\n");
      out.write("						<input type=\"text\" name=\"id\" class=\"box\">\r\n");
      out.write("					</td>\r\n");
      out.write("  				</tr>\r\n");
      out.write("  				<tr>\r\n");
      out.write("					<td width=\"150\" class=\"m3\">비밀번호</td>\r\n");
      out.write("					<td class=\"m3\">\r\n");
      out.write("						<input type=\"password\" name=\"passwd\" class=\"box\">\r\n");
      out.write("					</td>\r\n");
      out.write("  				</tr>\r\n");
      out.write("  				<tr>\r\n");
      out.write("					<td width=\"150\" class=\"m3\">주민번호</td>\r\n");
      out.write("					<td class=\"m3\">\r\n");
      out.write("						<input type=\"text\" name=\"ssn1\" class=\"box\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.ssn1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readOnly> -\r\n");
      out.write("				<input type=\"password\" name=\"ssn2\" class=\"box\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.ssn2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readOnly>\r\n");
      out.write("					</td>\r\n");
      out.write("  				</tr>\r\n");
      out.write("  				<tr>\r\n");
      out.write("					<td width=\"150\" class=\"m3\">이메일</td>\r\n");
      out.write("					<td class=\"m3\">\r\n");
      out.write("						<input type=\"text\" name=\"email\" class=\"box\">\r\n");
      out.write("					</td>\r\n");
      out.write("  				</tr>\r\n");
      out.write("  				<tr>\r\n");
      out.write("					<td width=\"150\" class=\"m3\">연락처</td>\r\n");
      out.write("					<td class=\"m3\">\r\n");
      out.write("						<input type=\"text\" name=\"hp1\" class=\"box\" size=\"3\" maxlength=\"3\"> -\r\n");
      out.write("						<input type=\"text\" name=\"hp2\" class=\"box\" size=\"4\" maxlength=\"4\"> -\r\n");
      out.write("						<input type=\"text\" name=\"hp3\" class=\"box\" size=\"4\" maxlength=\"4\">\r\n");
      out.write("					</td>\r\n");
      out.write("  				</tr>\r\n");
      out.write("  				<tr>\r\n");
      out.write("					<td colspan=\"2\" align=\"center\">\r\n");
      out.write("						<a href=\"javascript:check()\">[전송]</a>\r\n");
      out.write("						<a href=\"#\">[취소]</a>\r\n");
      out.write("					</td>\r\n");
      out.write("  				</tr>\r\n");
      out.write("  			</table>\r\n");
      out.write("		</form>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
